[project]
name = "foo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chevron-blue>=0.2.1,<0.3.0",
    "hatchling>=1.20.0,<2.0.0",
    "msgspec>=0.18.4,<0.19.0",
    "pypiserver>=2.0.1,<3.0.0",
    "pyyaml>=6.0.1,<7.0.0",
    "setuptools>=69.1.1,<70.0.0",
    "twine>=4.0.2,<5.0.0",
    "watchfiles>=0.21.0,<0.22.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
